# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Arrivify' do

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'
use_frameworks!
pod 'Alamofire', '~> 3.0'

end

target 'ArrivifyTests' do

end

target 'ArrivifyUITests' do

end

